AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://pmbrull-cloudformation-yaml.s3-us-west-2.amazonaws.com/templates/HA-webapp-vpc.yml
      Parameters:
        EnvironmentName: "Udacity-IAC-Project"
        VpcCIDR: "10.0.0.0/16"
        PublicSubnet1CIDR: "10.0.0.0/24"
        PublicSubnet2CIDR: "10.0.1.0/24"
        PrivateSubnet1CIDR: "10.0.2.0/24"
        PrivateSubnet2CIDR: "10.0.3.0/24"

Outputs:
  StackRef:
    Value: !Ref VPCStack